name: base_widgets
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0-63.1.beta <4.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  intl: ^0.18.1
  widgetbook_annotation: ^3.1.0
  widgetbook: ^3.4.1

dev_dependencies:
  build_runner:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  widgetbook_generator: ^3.3.0

flutter:
  uses-material-design: true
  assets:
    - assets/
